import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ChevronRight, Building2, ShieldCheck, Zap, Globe, Download, CheckCircle2, Info } from 'lucide-react';
import stateConfig from '@shared/state-config.json';
import ChatInterface from './components/ChatInterface';
import VerificationScreen from './components/VerificationScreen';
import axios from 'axios';
import { jsPDF } from 'jspdf';

type FlowState = 'landing' | 'chat' | 'verification' | 'success';

const App = () => {
  const [flow, setFlow] = useState<FlowState>('landing');
  const [selectedState, setSelectedState] = useState('');
  const [sessionId, setSessionId] = useState('');
  const [initialMessage, setInitialMessage] = useState('');
  const [formData, setFormData] = useState<any>(null);
  const [isStarting, setIsStarting] = useState(false);

  const handleStart = async () => {
    if (selectedState) {
      setIsStarting(true);
      try {
        const { data } = await axios.post('/api/formations/start', { state: selectedState });
        setSessionId(data.sessionId);
        setInitialMessage(data.initialMessage);
        setFlow('chat');
      } catch (error) {
        console.error('Failed to start formation:', error);
        setSessionId('demo-session');
        setInitialMessage(`Hi! I'll help you form an LLC in ${selectedState}. Let's start—what's your business name?`);
        setFlow('chat');
      } finally {
        setIsStarting(false);
      }
    }
  };

  const handleChatFinished = (data: any) => {
    setFormData(data);
    setFlow('verification');
  };

  const handleDownload = () => {
    if (formData) {
      const fileNameRaw = formData.businessName ? formData.businessName.replace(/\s+/g, '_') : 'My_LLC';

      // 1. Download JSON
      const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(formData, null, 2));
      const jsonAnchor = document.createElement('a');
      jsonAnchor.setAttribute("href", dataStr);
      jsonAnchor.setAttribute("download", `${fileNameRaw}_Filing_Data.json`);
      document.body.appendChild(jsonAnchor); 
      jsonAnchor.click();
      jsonAnchor.remove();

      // 2. Generate and Download Professional PDF
      const doc = new jsPDF();
      const margin = 20;

      // Header
      doc.setFont("helvetica", "bold");
      doc.setFontSize(22);
      doc.text("ARTICLES OF ORGANIZATION", margin, 30);
      
      doc.setFont("helvetica", "normal");
      doc.setFontSize(14);
      doc.text(`Jurisdiction: State of ${formData.state || selectedState || 'N/A'}`, margin, 45);
      
      // Section 1
      doc.setFont("helvetica", "bold");
      doc.setFontSize(12);
      doc.text("1. Name of Limited Liability Company", margin, 65);
      doc.setFont("helvetica", "normal");
      doc.text(`   ${formData.businessName || 'N/A'}`, margin, 75);
      
      // Section 2
      doc.setFont("helvetica", "bold");
      doc.text("2. Business Addresses", margin, 95);
      doc.setFont("helvetica", "normal");
      doc.text(`   Principal Office: ${formData.principalOfficeAddress || 'N/A'}`, margin, 105);
      
      // Section 3
      doc.setFont("helvetica", "bold");
      doc.text("3. Agent for Service of Process", margin, 125);
      doc.setFont("helvetica", "normal");
      doc.text(`   Name: ${formData.registeredAgentName || 'N/A'}`, margin, 135);
      doc.text(`   Address: ${formData.registeredAgentAddress || 'N/A'}`, margin, 145);
      
      // Section 4
      doc.setFont("helvetica", "bold");
      doc.text("4. Management / Member Structure", margin, 165);
      doc.setFont("helvetica", "normal");
      let currentY = 175;
      if (formData.members && Array.isArray(formData.members)) {
        formData.members.forEach((m: any) => {
          doc.text(`   - ${m.name} (${m.ownershipPercentage || 100}% Equity)`, margin, currentY);
          currentY += 10;
        });
      } else {
        doc.text(`   - Sole Member structure authorized.`, margin, currentY);
        currentY += 10;
      }

      // Section 5: Filing Preference
      currentY += 10;
      doc.setFont("helvetica", "bold");
      doc.text("5. Filing Preferences & Contact", margin, currentY);
      currentY += 10;
      doc.setFont("helvetica", "normal");
      
      const prefText = formData.filingPreference === 'agency' 
        ? "Platform Agency Filing Authorized" 
        : "Manual Filing Selected by Owner";
      doc.text(`   Execution Method: ${prefText}`, margin, currentY);
      currentY += 10;

      if (formData.filingPreference === 'agency' && formData.clientEmail) {
        doc.text(`   Authorizing Contact Email: ${formData.clientEmail}`, margin, currentY);
      }
      
      // Footer
      doc.setFont("helvetica", "italic");
      doc.setFontSize(10);
      doc.text("Securely generated by LLC-Flow Platform for official state filing preparation.", margin, 280);
      
      // Trigger PDF Browser Download
      doc.save(`${fileNameRaw}_Articles.pdf`);
    }
    
    setFlow('success');
  };

  return (
    <div className="min-h-screen bg-background text-foreground selection:bg-primary/20">
      <AnimatePresence mode="wait">
        {flow === 'landing' && (
          <motion.div
            key="landing"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -20 }}
            className="container max-w-6xl mx-auto px-4 py-20 flex flex-col items-center text-center space-y-12"
          >
            {/* Hero Section */}
            <div className="space-y-6 max-w-3xl">
              <motion.div
                initial={{ opacity: 0, scale: 0.9 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ delay: 0.2 }}
                className="inline-flex items-center space-x-2 px-4 py-2 rounded-full bg-primary/10 text-primary text-sm font-medium border border-primary/20 mb-4"
              >
                <Zap size={16} />
                <span>AI-Powered Business Formation</span>
              </motion.div>
              
              <h1 className="text-5xl md:text-7xl font-bold tracking-tight text-slate-900 leading-tight">
                LLC-Flow: Form Your <span className="text-primary italic">Dream</span> LLC in Minutes.
              </h1>
              
              <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
                No legal jargon, no complex forms. Just a quick chat with our AI agent to generate your professional Articles of Organization.
              </p>
            </div>

            {/* State Selection Card */}
            <motion.div
              initial={{ opacity: 0, y: 30 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.4 }}
              className="w-full max-w-md p-8 rounded-2xl glass shadow-2xl border border-white/20 space-y-6"
            >
              <div className="text-left space-y-2">
                <label className="text-sm font-semibold text-slate-600 ml-1">Select Your State</label>
                <select
                  value={selectedState}
                  onChange={(e) => setSelectedState(e.target.value)}
                  className="w-full h-14 px-4 rounded-xl border border-slate-200 bg-white/50 focus:ring-2 focus:ring-primary focus:border-transparent transition-all outline-none appearance-none cursor-pointer"
                >
                  <option value="" disabled>Choose a state...</option>
                  {Object.entries(stateConfig.states).map(([code, state]) => (
                    <option key={code} value={code}>
                      {state.name} ({code})
                    </option>
                  ))}
                </select>
              </div>

              <button
                onClick={handleStart}
                disabled={!selectedState || isStarting}
                className={`w-full h-14 rounded-xl font-bold flex items-center justify-center space-x-2 transition-all shadow-lg ${
                  selectedState && !isStarting
                    ? 'bg-primary text-white hover:bg-primary/90 hover:scale-[1.02] active:scale-[0.98]'
                    : 'bg-slate-200 text-slate-400 cursor-not-allowed'
                }`}
              >
                {isStarting ? (
                  <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                ) : (
                  <>
                    <span>Start Your Formation</span>
                    <ChevronRight size={20} />
                  </>
                )}
              </button>
              
              <p className="text-xs text-muted-foreground">
                Currently supporting Delaware and California. More states coming soon.
              </p>
            </motion.div>

            {/* Features Grid */}
            <div className="grid md:grid-cols-3 gap-8 w-full py-12">
              {[
                {
                  icon: <Building2 className="text-blue-500" />,
                  title: "Direct Data Collection",
                  desc: "We collect exactly what your state requires, nothing more."
                },
                {
                  icon: <ShieldCheck className="text-emerald-500" />,
                  title: "Verified Templates",
                  desc: "Generated documents follow official Secretary of State formats."
                },
                {
                  icon: <Globe className="text-purple-500" />,
                  title: "Manual Filing Instructions",
                  desc: "Step-by-step guidance on how to submit your documents."
                }
              ].map((feature, i) => (
                <div key={i} className="p-6 rounded-2xl bg-white border border-slate-100 shadow-sm hover:shadow-md transition-shadow text-left space-y-4">
                  <div className="w-12 h-12 rounded-xl bg-slate-50 flex items-center justify-center">
                    {feature.icon}
                  </div>
                  <h3 className="font-bold text-lg text-slate-800">{feature.title}</h3>
                  <p className="text-muted-foreground text-sm leading-relaxed">{feature.desc}</p>
                </div>
              ))}
            </div>
          </motion.div>
        )}

        {flow === 'chat' && (
          <motion.div
            key="chat"
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: -20 }}
            className="h-screen flex items-center justify-center p-4 bg-slate-50"
          >
            <ChatInterface 
              sessionId={sessionId} 
              initialMessage={initialMessage} 
              onFinished={handleChatFinished} 
            />
          </motion.div>
        )}

        {flow === 'verification' && (
          <VerificationScreen 
            formData={formData} 
            onEdit={() => setFlow('chat')} 
            onDownload={handleDownload} 
          />
        )}

        {flow === 'success' && (
          <motion.div
            key="success"
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1 }}
            className="container max-w-2xl mx-auto px-4 py-20 text-center space-y-8"
          >
            <div className="w-20 h-20 bg-emerald-100 text-emerald-600 rounded-full flex items-center justify-center mx-auto mb-6">
              <CheckCircle2 size={40} />
            </div>
            <h2 className="text-4xl font-bold">Formation Ready!</h2>
            <p className="text-xl text-muted-foreground">
              Your LLC formation pack is ready. Check your downloads for the PDF and instruction guide.
            </p>
            
            <div className="bg-white p-8 rounded-2xl border border-slate-100 text-left space-y-6 shadow-xl">
              <h3 className="font-bold text-xl flex items-center space-x-2">
                <Info className="text-primary" />
                <span>Next Steps (Manual Filing)</span>
              </h3>
              <ol className="space-y-4 text-slate-700">
                <li className="flex space-x-3">
                  <span className="w-6 h-6 rounded-full bg-primary/10 text-primary flex-shrink-0 flex items-center justify-center font-bold text-sm">1</span>
                  <span>Visit the <strong>{stateConfig.states[selectedState as keyof typeof stateConfig.states].name} Secretary of State</strong> website.</span>
                </li>
                <li className="flex space-x-3">
                  <span className="w-6 h-6 rounded-full bg-primary/10 text-primary flex-shrink-0 flex items-center justify-center font-bold text-sm">2</span>
                  <span>Upload your generated <strong>Articles of Organization</strong> PDF.</span>
                </li>
                <li className="flex space-x-3">
                  <span className="w-6 h-6 rounded-full bg-primary/10 text-primary flex-shrink-0 flex items-center justify-center font-bold text-sm">3</span>
                  <span>Pay the <strong>${stateConfig.states[selectedState as keyof typeof stateConfig.states].filingFee}</strong> filing fee.</span>
                </li>
              </ol>
            </div>

            <button
              onClick={() => setFlow('landing')}
              className="px-8 h-14 rounded-xl bg-slate-900 text-white font-bold hover:bg-slate-800 transition-all"
            >
              Start Another LLC
            </button>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Footer */}
      <footer className="py-12 border-t border-slate-100 text-center text-sm text-muted-foreground">
        <p>&copy; 2026 LLC-Flow. Not a law firm. No legal advice provided.</p>
      </footer>
    </div>
  );
};

export default App;
